title: STAT 207: Advanced Statistical Computing # your name (or website title) here
logo: "/images/convex-optimization-image.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Webpage for course materials and schedule
  <br><br>
  <a href="/Syllabi/Syllabus_STAT207_Sp23.pdf">Spring 2023 Syllabus</a>
  <br><br>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
