title: STAT 207: Advanced Statistical Computing # your name (or website title) here
# logo: "/images/IMG_1153.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Webpage for course materials and schedule
  <br><br>
  <a href="/Syllabi/Syllabus_STAT207_Sp23.pdf">Spring 2023 Syllabus</a>
  <br><br>
  <a href="https://ph.ucla.edu/faculty/fei">Webpage at UCLA</a> 
  <br><br>
  <a href="https://sites.google.com/view/feizhepku">Research</a> 
  <br><br>
  <a href="https://sites.google.com/view/feizhepku">Teaching</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
